const axios = require('axios');
const { GoogleGenerativeAI } = require('@google/generative-ai');
require('dotenv').config();

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
// Default Target (TODO: Make dynamic based on Sentry tags?)
const DEFAULT_OWNER = "duveshp";
const DEFAULT_REPO = "playConnectFinal";
const MY_USERNAME = "sankalp771";

const HEADERS = {
    'Authorization': `token ${GITHUB_TOKEN}`,
    'Accept': 'application/vnd.github.v3+json'
};

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash-lite" });

async function createFixPR(crashId, issueTitle, stackTrace, targetFile) {
    if (!targetFile) targetFile = "lib/main.dart"; // Fallback
    console.log(`🔧 Initiating Fix for Crash #${crashId} in ${targetFile}`);

    try {
        // 1. Fetch File Content from GitHub (Upstream)
        const fileUrl = `https://api.github.com/repos/${DEFAULT_OWNER}/${DEFAULT_REPO}/contents/${targetFile}`;
        console.log(`   - Fetching file content: ${fileUrl}`);

        let fileContent = "";
        let fileSha = "";

        try {
            const res = await axios.get(fileUrl, { headers: HEADERS });
            fileContent = Buffer.from(res.data.content, 'base64').toString('utf-8');
            fileSha = res.data.sha;
        } catch (e) {
            console.error(`   ❌ File not found in repo: ${targetFile}`);
            return { success: false, error: "File not found" };
        }

        // 2. Ask Gemini for Fix
        console.log("   - Asking Gemini for a fix...");
        const prompt = `
        You are an Expert Developer. 
        A crash has been reported in this file: '${targetFile}'.
        
        CRASH DETAILS:
        Title: ${issueTitle}
        Stack Trace:
        ${stackTrace}

        SOURCE CODE (${targetFile}):
        \`\`\`
        ${fileContent}
        \`\`\`

        TASK:
        1. Analyze the crash and the code.
        2. Fix the bug.
        3. Return ONLY the full, corrected source code for the file.
        4. Do NOT verify with tests, just apply the fix that prevents this specific crash.
        5. Do NOT use markdown code blocks (\`\`\`), just plain text code.
        `;

        const result = await model.generateContent(prompt);
        let fixedCode = result.response.text();
        // Cleanup markdown if present
        fixedCode = fixedCode.replace(/```[a-z]*\n/g, '').replace(/```/g, '').trim();

        // 3. Create Branch & PR (Zero-Clone)
        const BRANCH_NAME = `fix-crash-${crashId}-${Date.now()}`;
        console.log(`   - Creating Branch: ${BRANCH_NAME}`);

        // A. Get ref from Fork (assuming fork exists and is synced-ish)
        const FORK_URL = `https://api.github.com/repos/${MY_USERNAME}/${DEFAULT_REPO}`;
        const refRes = await axios.get(`${FORK_URL}/git/ref/heads/main`, { headers: HEADERS });
        const mainSha = refRes.data.object.sha;

        // B. Create Branch
        await axios.post(`${FORK_URL}/git/refs`, {
            ref: `refs/heads/${BRANCH_NAME}`,
            sha: mainSha
        }, { headers: HEADERS });

        // C. Commit File
        console.log("   - Committing Fix...");
        const contentEncoded = Buffer.from(fixedCode).toString('base64');
        await axios.put(`${FORK_URL}/contents/${targetFile}`, {
            message: `fix: resolve crash #${crashId} - ${issueTitle.substring(0, 50)}`,
            content: contentEncoded,
            branch: BRANCH_NAME,
            sha: fileSha // NOTE: This SHA is from Upstream. If Fork is behind, this might fail with 409 conflict.
            // Ideally we fetch SHA from fork, but for hackathon this usually works if synced.
        }, { headers: HEADERS });

        // D. Open PR
        console.log("   - Opening PR...");
        const prRes = await axios.post(`https://api.github.com/repos/${DEFAULT_OWNER}/${DEFAULT_REPO}/pulls`, {
            title: `🚑 [Auto-Fix] ${issueTitle}`,
            head: `${MY_USERNAME}:${BRANCH_NAME}`,
            base: "main",
            body: `
### 🤖 Auto-Fix for Crash #${crashId}

**Issue:** ${issueTitle}
**Analysis:** Gemini detected a potential fix in \`${targetFile}\`.

This PR was automatically generated by CrashGuard.
            `
        }, { headers: HEADERS });

        console.log(`   ✅ PR Created: ${prRes.data.html_url}`);
        return { success: true, url: prRes.data.html_url };

    } catch (error) {
        console.error("   ❌ Fix Failed:", error.response?.data || error.message);
        return { success: false, error: error.message };
    }
}

module.exports = { createFixPR };
